import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <img src="" alt="" />
          <h2>Event in London</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sapiente odio ab, tempora magni porro ducimus. Tenetur, commodi excepturi fugit ipsum recusandae praesentium placeat facilis magni, ipsam explicabo, consequuntur sapiente nobis?
          Quibusdam quasi vero temporibus. Reprehenderit impedit, dicta facere fugiat, qui cum laudantium eius nemo nulla ipsam maiores obcaecati culpa architecto deserunt aliquam ab sequi incidunt sapiente! Reiciendis debitis labore laborum?
          Id dolor reprehenderit quia, dolore non maiores commodi quos totam nihil harum libero, aut quis tempora dolorem consectetur blanditiis molestiae rerum. Voluptates quibusdam repudiandae ipsa harum praesentium, sed in labore!
          Maiores praesentium incidunt, quo quos architecto aperiam ea suscipit, facere qui minima blanditiis. Officia, laboriosam tempora! Culpa rerum, reprehenderit voluptas facilis ullam libero ipsum nisi velit accusamus? Ad, impedit reprehenderit.
          Inventore sed incidunt cum nam tenetur consectetur aut in quo, illo officiis iste suscipit explicabo atque deleniti, quia deserunt odit id temporibus tempora esse itaque sint perferendis cumque. Veniam, in.
          </p>
        </a>
        <a href="">
          <img src="" alt="" />
          <h2>Event in San Francisco</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sapiente odio ab, tempora magni porro ducimus. Tenetur, commodi excepturi fugit ipsum recusandae praesentium placeat facilis magni, ipsam explicabo, consequuntur sapiente nobis?
          Quibusdam quasi vero temporibus. Reprehenderit impedit, dicta facere fugiat, qui cum laudantium eius nemo nulla ipsam maiores obcaecati culpa architecto deserunt aliquam ab sequi incidunt sapiente! Reiciendis debitis labore laborum?
          Id dolor reprehenderit quia, dolore non maiores commodi quos totam nihil harum libero, aut quis tempora dolorem consectetur blanditiis molestiae rerum. Voluptates quibusdam repudiandae ipsa harum praesentium, sed in labore!
          Maiores praesentium incidunt, quo quos architecto aperiam ea suscipit, facere qui minima blanditiis. Officia, laboriosam tempora! Culpa rerum, reprehenderit voluptas facilis ullam libero ipsum nisi velit accusamus? Ad, impedit reprehenderit.
          Inventore sed incidunt cum nam tenetur consectetur aut in quo, illo officiis iste suscipit explicabo atque deleniti, quia deserunt odit id temporibus tempora esse itaque sint perferendis cumque. Veniam, in.
          </p>
        </a>
        <a href="">
          <img src="" alt="" />
          <h2>Event in Barcelona</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sapiente odio ab, tempora magni porro ducimus. Tenetur, commodi excepturi fugit ipsum recusandae praesentium placeat facilis magni, ipsam explicabo, consequuntur sapiente nobis?
          Quibusdam quasi vero temporibus. Reprehenderit impedit, dicta facere fugiat, qui cum laudantium eius nemo nulla ipsam maiores obcaecati culpa architecto deserunt aliquam ab sequi incidunt sapiente! Reiciendis debitis labore laborum?
          Id dolor reprehenderit quia, dolore non maiores commodi quos totam nihil harum libero, aut quis tempora dolorem consectetur blanditiis molestiae rerum. Voluptates quibusdam repudiandae ipsa harum praesentium, sed in labore!
          Maiores praesentium incidunt, quo quos architecto aperiam ea suscipit, facere qui minima blanditiis. Officia, laboriosam tempora! Culpa rerum, reprehenderit voluptas facilis ullam libero ipsum nisi velit accusamus? Ad, impedit reprehenderit.
          Inventore sed incidunt cum nam tenetur consectetur aut in quo, illo officiis iste suscipit explicabo atque deleniti, quia deserunt odit id temporibus tempora esse itaque sint perferendis cumque. Veniam, in.
          </p>
        </a>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
}
